{
  "hash": "704095b0105981b55a9103f5b146555b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Crosswalking ORION resources to measure open access to biomedical research literature\"\nauthor:\n  - name: Najko Jahn\n    orcid: 0000-0001-5105-1463\n  - name: Bianca Kramer\n    orcid: 0000-0002-5965-6560\n  - name: Cameron Neylon\n    orcid: 0000-0002-0068-716X\n  - name: Nick Haupka\n    orcid: 0009-0002-6478-6789\ndate: \"2026-03-13\"\nabstract: \"This tutorial demonstrates how to crosswalk various ORION resources. The focus is on funder and open access information for biomedical journal literature. Using the National Institutes of Health (NIH) and the European Commission (EC) as examples, the tutorial shows how to combine several data sources on BigQuery, including Crossref, OpenAIRE, OpenAlex, and open access agreement data from cOAlition S. The analysis covers more than 800,000 articles in PubMed, revealing notable differences in open access uptake between NIH- and EC-supported biomedical research.\"\ncategories: [tutorial, open access, funder info]\nexecute:\n  cache: true\nstatus: \"wip\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Introduction\n\nThis notebook shows how several open research information resources provided by the [ORION community](https://orion-dbs.community/) on Google BigQuery can be used to measure open access by funder over time.\nWe use a comparison of NIH- and European Commission-supported biomedical research literature to illustrate the approach.\n[Transformative agreements have played an important role in Europe](https://doi.org/10.1162/qss_a_00348) for several years, and [recent discussions around the NIH open access policy and price caps for publication fees](https://www.science.org/content/article/nih-s-proposed-caps-open-access-publishing-fees-roil-scientific-community) raise the question about the role of similar agreements in the US.\n\n## Overview of data sources\n\nUsing this policy debate as a starting point, this notebook combines the following sources into a unified dataset on open access in biomedical research literature, with a particular focus on publisher-provided open access through transformative agreements.\n\n*Identifying grant-supported biomedical literature*\n\n- **[PubMed](https://pubmed.ncbi.nlm.nih.gov/)**: Our starting point, which is used to retrieve [NIH grant-supported publications](https://pubmed.ncbi.nlm.nih.gov/?term=NIH%5BGrants+and+Funding%5D) and as a standard source for biomedical literature. PubMed is not available through one of ORION's data offerings, so data are retrieved via the [Entrez API](https://www.ncbi.nlm.nih.gov/home/develop/api/). PubMed identifiers (PMIDs) serve as the linking key for biomedical research records.\n::: {.column-margin}\nThe script used can be found [here](fetch_pmid_nih.R).\n:::\n- **[OpenAIRE](https://www.openaire.eu/)**: The [OpenAIRE graph](https://www.openaire.eu/), provided by [Sesame Open Science](https://orion-dbs.community/collections/sos/#openaire), is used to identify publications supported by the European Commission. OpenAIRE also contains PMIDs for PubMed-indexed articles, which allows filtering of to biomedical literature and linking to the other sources.\n\n*Publication metadata*\n\n- **[OpenAlex](https://openalex.org/)**: The primary source for bibliographic metadata in this tutorial. OpenAlex records also include PMIDs as identifiers. Here, we will use the [SUB Göttingen OpenAlex offering](https://orion-dbs.community/collections/subugoe/#openalex_walden).\n- **[Crossref](https://www.crossref.org/)**: As provided by [SUB Göttingen](https://orion-dbs.community/collections/subugoe/#cr_instant). Useful for publisher disambiguation, because Crossref provides more consistent publisher names than OpenAlex.\n- **Document classification**: A document classification dataset, developed as part of the [German Competence Network for Bibliometrics](https://open-bibliometrics.de/posts/20250717-DocumentTypeClassifier/) and provided by SUB Göttingen, is used to restrict the sample to original research articles.\n\n*Open access information*\n\n- **[OpenAlex](https://openalex.org/)**: Provides article- and journal-level open access status.\n- **[cOAlition S Journal Checker Tool data](https://journalcheckertool.org/transformative-agreements/)**: Contains institution- and journal-level data crowd-sourced from library consortia. [SUB Göttingen consolidates this information and links articles to agreements](https://open-bibliometrics.de/posts/20250509-tarelease/). This tutorial shows how that matching can be carried out in Google BigQuery.\n\n## Data gathering steps\n\n### Setup\n\nAs a notebook software, we use [Quarto](https://quarto.org/). Acutally, the ORION website is also build with Quarto.\n\nTo query BigQuery from within our Quarto notebook, we use the R [`bigrquery`](https://bigrquery.r-dbi.org/) package via the DBI interface. The connection is established as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(bigrquery)\nlibrary(DBI)\nlibrary(countrycode)\n\n# Connect to GBQ with billing project from SUB Göttingen,\n# You have to use your own :-)\nbq_con <- dbConnect(\n  bigrquery::bigquery(),\n  project = \"subugoe-collaborative\",\n  dataset = \"openalex\",\n  billing = \"subugoe-collaborative\"\n)\n```\n:::\n\n\nWe also define a custom plot theme, inspired by the style used by [Our World in Data](https://ourworldindata.org/).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_theme <- function(base_size = 12) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      panel.grid.major.x = element_blank(),\n      panel.grid.minor.x = element_blank(),\n      panel.grid.minor.y = element_blank(),\n      panel.grid.major.y = element_line(color = \"grey85\", linewidth = 0.3),\n      axis.line.x = element_line(color = \"grey40\", linewidth = 0.4),\n      axis.ticks.x = element_line(color = \"grey40\", linewidth = 0.3),\n      axis.ticks.length.x = unit(0.15, \"cm\"),\n      axis.ticks.y = element_blank(),\n      axis.text = element_text(color = \"grey30\", size = rel(0.9)),\n      axis.title.y = element_text(color = \"grey30\", size = rel(0.95), margin = margin(r = 10)),\n      plot.title = element_text(face = \"bold\", size = rel(1.1), color = \"grey10\", margin = margin(b = 8)),\n      plot.title.position = \"plot\",\n      plot.caption = element_text(hjust = 1, size = rel(0.7), color = \"grey50\", margin = margin(t = 12)),\n      plot.caption.position = \"plot\",\n      legend.position = \"top\",\n      plot.margin = margin(10, 10, 10, 10)\n    )\n}\n```\n:::\n\n\n### Create a publication metadata set\n\nThis section describes how we assembled the analytical dataset, combining grant funding information from PubMed and OpenAIRE with publication metadata from OpenAlex and Crossref.\n\nIt is generally good practice to begin by creating a focused subset of publications that contains only the columns needed for your analysis.\nThis reduces query costs, keeps the working dataset to a manageable size, and keeps a local subset of the raw metadata save.\n\nOur first step is to build a publication dataset enriched with grant funding information from the NIH and the European Commission.\nBecause PubMed is not yet part of ORION, NIH funding data are retrieved directly from PubMed via the Entrez API.\n\nThe result is a list of PMIDs representing NIH-supported publications, which we then upload to BigQuery.\n\n::: {.column-margin}\nHere is the [R script](fetch_pmid_nih.R) and the resulting [PMID list](nih_pmids_2018_2024.txt) used.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npmids_nih <- read_lines(\"nih_pmids_2018_2024.txt\")\ndbWriteTable(bq_con, # Our BQ connections\n             \"subugoe-collaborative.resources.nih_pmids_2018_2024\", # Table name\n             tibble::tibble(pmids_nih = pmids_nih), # PMIDs in rectangular format with column name\n             overwrite = TRUE\n             )\n```\n:::\n\n\nIn total, PubMed indexed 824060 publications with NIH support between 2018 and 2024.\n\nNext, we combine this list with OpenAIRE, [the most comprehensive source for EC-funded publications](https://arxiv.org/pdf/2109.10638),  to add European Commission-supported biomedical literature, and with OpenAlex and Crossref to obtain full publication metadata.\n\nThe resulting table is stored as `subugoe-collaborative.resources.oa_tutorial_md_raw`, and is publicly accessible. You will need to substitute your own dataset name.\n\n\n::: {.cell}\n\n```{.sql .cell-code}\nCREATE OR REPLACE TABLE `subugoe-collaborative.resources.oa_tutorial_md_raw` AS (\n\nWITH openaire_funders AS (\n  SELECT DISTINCT\n    pid.value AS pmid,\n    fund.name AS funder\n  FROM `sos-datasources.openaire.project_20260129` AS proj,\n    UNNEST(fundings) AS fund\n  INNER JOIN `sos-datasources.openaire.relation_product_project_20260129` AS pub_proj\n    ON proj.id = pub_proj.target\n  INNER JOIN `sos-datasources.openaire.publication_20260129` AS pub\n    ON pub_proj.source = pub.id,\n    UNNEST(pub.pids) AS pid\n  WHERE fund.name IN ('European Commission')\n    AND pid.scheme = 'pmid'\n),\n\nnih_funders AS (\n  SELECT DISTINCT\n    CAST(pmids_nih AS STRING) AS pmid\n  FROM `subugoe-collaborative.resources.nih_pmids_2018_2024`\n),\n\nall_funders AS (\n  SELECT pmid, 'European Commission' AS funder\n  FROM openaire_funders\n  UNION ALL\n  SELECT pmid, 'NIH' AS funder\n  FROM nih_funders\n)\n\nSELECT DISTINCT\n    oalex.id,\n    oalex.doi,\n    oalex.ids.pmid,\n    oalex.ids.pmcid,\n    publication_year,\n    publication_date,\n    primary_location.source.issn_l AS issn_l,\n    oalex.primary_location.source.host_organization_name AS oalex_publisher,\n    cr.publisher AS cr_publisher,\n    primary_location.source.is_in_doaj AS is_in_doaj,\n    open_access.oa_status AS oa_status,\n    country AS country_code,\n    inst.ror,\n    af.funder AS funders\n  FROM `subugoe-collaborative.openalex_walden.works` AS oalex\n  LEFT JOIN\n    UNNEST(authorships) AS au WITH OFFSET AS pos\n  LEFT JOIN\n    UNNEST(au.countries) AS country\n  LEFT JOIN\n    UNNEST(au.institutions) AS inst\n  LEFT JOIN `subugoe-collaborative.resources.document_classification_september25` AS doctype_classifier\n    ON oalex.doi = doctype_classifier.doi\n  INNER JOIN `subugoe-collaborative.cr_instant.snapshot` AS cr\n    ON LOWER(oalex.doi) = LOWER(cr.doi)\n  LEFT JOIN all_funders AS af\n    ON REGEXP_EXTRACT(oalex.ids.pmid, r'(\\d+)$') = af.pmid\n  WHERE\n      pos = 0\n    AND primary_location.source.type = \"journal\"\n    AND is_paratext = FALSE\n    AND oalex.type IN ('article','review')\n    AND is_research IS NOT FALSE\n    AND is_xpac = FALSE\n    AND (\n      NOT REGEXP_CONTAINS(oalex.biblio.issue, '^[a-zA-Z]')\n      OR oalex.biblio.issue IS NULL)\n    AND (\n      NOT REGEXP_CONTAINS(oalex.title, '[0-9]{3} pp.'))\n    AND publication_year BETWEEN 2018 AND 2025\n)\n```\n:::\n\n\n\nThe query uses Common Table Expressions (CTEs), introduced with `WITH`, to build up the dataset in stages.\nThe first CTE, `openaire_funders`, extracts EC-funded publications from OpenAIRE by unnesting the fundings array, filtering for the European Commission, and joining to the OpenAIRE publication and relation tables to retrieve the associated PMIDs.\nThe second CTE, `nih_funders`, reads the PMID list we uploaded in the previous step.\nBoth are combined in `all_funders` using `UNION ALL`.\n\nThe main query retrieves metadata for all journal articles in the OpenAlex snapshot and joins the funder information.\nSeveral filters are applied to keep the dataset focused on relevant publications: only journal articles and reviews are included; first author affiliations are used (identified via `WITH OFFSET` because the author position field was not available in this snapshot); and a set of pattern-based exclusions removes conference proceedings and other non-standard records.\nCrossref is used as the source for publisher names, as it provides more consistent disambiguation than OpenAlex, which can split the same publisher across multiple imprints.\nThe dataset covers publications from 2018 to 2025.\n\n### Estimate articles covered by transformative agreements\n\nNext, we estimate how many open access articles were enabled by a transformative agreement, following the method described by [Jahn (2025)](https://link.springer.com/article/10.1007/s11192-025-05390-3).\nBecause of a lack of open access invoicing data, ususally not shared by libraries and publishers, various metadata sources ar ematched to obtain an estiamtion. Such an appraoch [has been proven to provide](https://doi.org/10.1162/QSS.a.24) robust results, but will likely underestimate the overall number of articles enabled by an angreements.\n\nThe query draws on several datasets from the Journal Checker Tool, provided by SUB Göttingen as part of the open bibliometric data offerings from the German Competence Network for Bibliometrics.\n\n\n::: {.cell}\n\n```{.sql .cell-code}\nCREATE OR REPLACE TABLE `subugoe-collaborative.resources.oa_tutorial_jct_articles` AS (\nWITH\n  -- Enrich ROR variants from associated institutions\n  obtain_associated_ror_ids AS (\n    SELECT\n      esac_id,\n      jct_inst.ror_id AS ror_jct,\n      inst.ror AS ror_associated\n    FROM\n      `subugoe-collaborative.openbib.jct_institutions` AS jct_inst\n    LEFT JOIN\n      `subugoe-collaborative.openalex.institutions` AS oalex_inst\n    ON\n      jct_inst.ror_id = oalex_inst.ror\n    LEFT JOIN\n      UNNEST(oalex_inst.associated_institutions) AS inst\n  ),\n\n  create_matching_table AS (\n    SELECT esac_id, 'ror_jct' AS ror_type, ror_jct AS ror\n    FROM obtain_associated_ror_ids\n    UNION ALL\n    SELECT esac_id, 'ror_associated' AS ror_type, ror_associated AS ror\n    FROM obtain_associated_ror_ids\n  ),\n\n  enriched_ror_variants AS (\n    SELECT DISTINCT\n      create_matching_table.*,\n      DATE(jct_inst.start_date) AS start_date,\n      DATE(jct_inst.end_date) AS end_date\n    FROM create_matching_table\n    INNER JOIN `subugoe-collaborative.openbib.jct_esac` AS jct_inst\n      ON create_matching_table.esac_id = jct_inst.id\n  ),\n\n  journal_agreements AS (\n    SELECT\n      j.issn_l,\n      e.id AS esac_id\n    FROM `subugoe-collaborative.openbib.jct_journals` AS j\n    INNER JOIN `subugoe-collaborative.openbib.jct_esac` AS e\n      ON j.esac_id = e.id\n  )\n\nSELECT DISTINCT\n  md.id,\n  md.doi,\n  md.issn_l AS matching_issn_l,\n  md.ror AS matching_ror,\n  erv.ror_type,\n  erv.esac_id,\n  erv.start_date,\n  erv.end_date,\n  md.publication_date\nFROM `subugoe-collaborative.resources.oa_tutorial_md_raw` AS md\nINNER JOIN journal_agreements AS ja\n  ON md.issn_l = ja.issn_l\nINNER JOIN enriched_ror_variants AS erv\n  ON md.ror = erv.ror\n  AND ja.esac_id = erv.esac_id\nWHERE\n  md.ror IS NOT NULL\n  AND md.issn_l IS NOT NULL\n  AND (PARSE_DATE('%Y-%m-%d', md.publication_date) >= erv.start_date OR erv.start_date IS NULL)\n  AND (PARSE_DATE('%Y-%m-%d', md.publication_date) <= erv.end_date OR erv.end_date IS NULL)\n  -- Only TA OA articles\n  AND oa_status IN ('gold', 'hybrid')\nORDER BY erv.esac_id, md.publication_date\n)\n```\n:::\n\n\nWith these two datasets in place, we are ready to proceed with the funder-specific open access analysis.\n\n### Create the analytical dataset: funder view\n\nThe following query combines the publication metadata table with the transformative agreement articles table to count articles by funder, publication year, and open access type.\nIt also calculates the total number of articles per funder and year, which serves as the denominator for open access proportions.\n\nThe analysis focuses on articles made freely available on the journal website, covering gold open access in DOAJ-listed journals, hybrid open access, and diamond open access.\nRepository-based open access, such as deposits in PubMed Central, is not distinguished further and is grouped into the \"Other\" category.\nThe same accounts for bronze, many biomedical journals make back issues openly available after an embargo period to comply with NIH open access policies prior 2025, which OpenAlex tags as bronze.\n\n\n::: {.cell output.var='funding_oa'}\n\n```{.sql .cell-code}\nWITH\n  oa AS (\n    SELECT\n      publication_year,\n      funders,\n      CASE\n        WHEN (is_in_doaj = TRUE AND oa_status = 'gold') THEN 'gold_is_in_doaj'\n        WHEN (is_in_doaj = TRUE AND oa_status = 'diamond')\n          THEN 'diamond_is_in_doaj'\n        WHEN oa_status = 'hybrid' THEN 'hybrid_oa'\n        WHEN oa_status != 'closed' THEN 'other_oa'\n        END AS oa_type,\n      CASE\n        WHEN jct.doi IS NOT NULL THEN TRUE\n        ELSE FALSE\n        END AS enabled_ta,\n      COUNT(DISTINCT md.pmid) AS n_oa_articles\n    FROM `subugoe-collaborative.resources.oa_tutorial_md_raw` AS md\n    LEFT JOIN\n      (\n        SELECT DISTINCT doi\n        FROM `subugoe-closed.apc_science.jct_articles`\n      ) AS jct\n      USING (doi)\n    WHERE funders IS NOT NULL\n    GROUP BY\n      publication_year,\n      funders,\n      oa_type,\n      enabled_ta\n  ),\n  total AS (\n    SELECT\n      publication_year,\n      funders,\n      COUNT(DISTINCT pmid) AS articles\n    FROM `subugoe-collaborative.resources.oa_tutorial_md_raw`\n    GROUP BY\n      publication_year,\n      funders\n  )\nSELECT\n  total.publication_year,\n  total.funders,\n  total.articles,\n  oa.n_oa_articles,\n  oa.oa_type,\n  oa.enabled_ta\nFROM total\nLEFT JOIN oa\n  ON\n    total.publication_year = oa.publication_year\n    AND total.funders = oa.funders\nWHERE total.funders IS NOT NULL AND total.publication_year < 2025\nORDER BY total.publication_year DESC\n```\n:::\n\n\nThe query result is stored in an R object called `funding_oa` for further local analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfunding_oa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 108 × 6\n   publication_year funders            articles n_oa_articles oa_type enabled_ta\n              <int> <chr>                 <int>         <int> <chr>   <lgl>     \n 1             2024 NIH                   89834         34745 other_… FALSE     \n 2             2024 NIH                   89834          5062 <NA>    FALSE     \n 3             2024 NIH                   89834          2500 diamon… FALSE     \n 4             2024 NIH                   89834         30187 gold_i… FALSE     \n 5             2024 NIH                   89834          1218 gold_i… TRUE      \n 6             2024 NIH                   89834          3241 hybrid… TRUE      \n 7             2024 NIH                   89834         12750 hybrid… FALSE     \n 8             2024 NIH                   89834           131 other_… TRUE      \n 9             2024 European Commissi…    26958          3102 other_… FALSE     \n10             2024 European Commissi…    26958          1348 <NA>    FALSE     \n# ℹ 98 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year <- funding_oa |>\n  filter(!is.na(oa_type)) |>\n  summarise(n_oa = sum(n_oa_articles),\n            .by = c(publication_year, funders, articles)\n            ) |>\n  mutate(oa_prop = n_oa / articles)\n```\n:::\n\n\nThe following figure illustrates the relative growth of open access, comparing biomedical research articles acknowledging support from the European Commission and the NIH.\nIt is evident that both funders have similar open access shares of over 90%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year |>\n  ggplot(aes(publication_year, oa_prop, group = funders, color = funders)) +\n  geom_line() +\n  geom_point() +\n  scale_y_continuous(\"Open Access (in%)\", labels = scales::percent_format()) +\n  scale_color_manual(NULL,\n    values = c(\n      \"NIH\" = \"#323a45\",\n      \"European Commission\" = \"#F8AE21\"\n    )) +\n  labs(x = NULL,\n       title = \"Open Access to biomedical research literature\",\n       subtitle = \"Journal articles and reviews in PubMed\",\n       caption = \"Data sources: PubMed, OpenAIRE, OpenAlex.\") +\n  my_theme()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/oa_by_year_rel-1.png){width=2100}\n:::\n:::\n\n\nThe next figure shows the absolute development.\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year |>\n  ggplot(aes(publication_year, n_oa, group = funders, color = funders)) +\n  geom_line() +\n  geom_point() +\n  scale_y_continuous(\"Open Access\", labels = scales::label_number(big.mark = \",\"), limits = c(0, NA), expand = c(0, 0)) +\n  scale_color_manual(NULL,\n    values = c(\n      \"NIH\" = \"#323a45\",\n      \"European Commission\" = \"#F8AE21\"\n    )) +\n  labs(x = NULL,\n       title = \"Open Access to biomedical research literature\",\n       subtitle = \"Journal articles and reviews in PubMed\",\n       caption = \"Data sources: PubMed, OpenAIRE, OpenAlex.\") +\n  my_theme()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/oa_by_year_abs-1.png){width=2100}\n:::\n:::\n\n\nNext, we break down open access by business model. Four categories are distinguished using a combination of OpenAlex data and estimates derived from the Coalition S Transformative Agreement data:\n\n- **APC**: gold or hybrid open access, not via a transformative agreement\n- **Transformative Agreement**: gold or hybrid open access enabled by a transformative agreement\n- **Diamond OA**: diamond open access (no article processing charge)\n- **Other**: all remaining open access routes (e.g. via PubMed Central)\n\nNote that the focus is on publisher open access business models, and [OpenAlex open access status definition favors publisher-provided open access](https://help.openalex.org/hc/en-us/articles/24347035046295-Open-Access-OA), so articles in PMC repositories are accounted when there was no open version on a publisher website.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year_and_type <- funding_oa |>\n  filter(!is.na(oa_type)) |>\n  mutate(oa_cat = case_when(\n    oa_type %in% c(\"gold_is_in_doaj\", \"hybrid_oa\") & enabled_ta == FALSE ~ \"APC\",\n    oa_type %in% c(\"gold_is_in_doaj\", \"hybrid_oa\") & enabled_ta == TRUE ~ \"Transformative Agreement\",\n    oa_type == \"diamond_is_in_doaj\" ~ \"Diamond OA\",\n    .default = \"Other\")\n) |> summarise(n_oa = sum(n_oa_articles),\n            .by = c(publication_year, funders, articles, oa_cat)\n            ) |>\n  mutate(oa_prop = n_oa / articles,\n             oa_cat = factor(oa_cat, levels = c(\"APC\", \"Transformative Agreement\", \"Diamond OA\", \"Other\")))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year_and_type\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 56 × 6\n   publication_year funders             articles oa_cat             n_oa oa_prop\n              <int> <chr>                  <int> <fct>             <int>   <dbl>\n 1             2024 NIH                    89834 Other             34876  0.388 \n 2             2024 NIH                    89834 Diamond OA         2500  0.0278\n 3             2024 NIH                    89834 APC               42937  0.478 \n 4             2024 NIH                    89834 Transformative A…  4459  0.0496\n 5             2024 European Commission    26958 Other              3199  0.119 \n 6             2024 European Commission    26958 Diamond OA          740  0.0275\n 7             2024 European Commission    26958 Transformative A…  8548  0.317 \n 8             2024 European Commission    26958 APC               13123  0.487 \n 9             2023 NIH                    97415 Other             43969  0.451 \n10             2023 NIH                    97415 Diamond OA         1948  0.0200\n# ℹ 46 more rows\n```\n\n\n:::\n:::\n\n\nThe following two plots show the same breakdown as proportions and as absolute counts, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year_and_type |>\n  ggplot(aes(publication_year, oa_prop, fill = fct_rev(oa_cat))) +\n  geom_area(color = \"black\", linewidth = 0.2) +\n  facet_wrap(~funders) +\n  scale_y_continuous(\"Open Access (in%)\", labels = scales::percent_format(), limits = c(0, 1),\n                   expand = c(0, 0)) +\n  scale_fill_manual(\"OA model\",\n    values = c(\n      \"APC\" = \"#0E6BA0\",\n      \"Transformative Agreement\" = \"#30C0D2\",\n      \"Diamond OA\" = \"#E2A3A4\",\n      \"Other\" = \"#AEACA0\"\n    )) +\n  labs(x = NULL,\n       title = \"Open Access to grant-supported biomedical research literature\",\n       subtitle = \"Journal articles and reviews in PubMed\",\n       caption = \"Data sources: PubMed, OpenAIRE, OpenAlex, cOAlition S Journal Checker Tool.\") +\n  my_theme() +\n  guides(fill = guide_legend(reverse = TRUE))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/oa_by_year_type_rel-1.png){width=2400}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noa_by_year_and_type |>\n  ggplot(aes(publication_year, n_oa, fill = fct_rev(oa_cat))) +\n  geom_area(color = \"black\", linewidth = 0.2) +\n  facet_wrap(~funders) +\n  scale_y_continuous(\"Open Access\", labels = scales::label_number(big.mark = \",\"),\n                     limits = c(0, NA), expand = c(0, 0)) +\n  scale_fill_manual(\"OA model\",\n    values = c(\n      \"APC\" = \"#0E6BA0\",\n      \"Transformative Agreement\" = \"#30C0D2\",\n      \"Diamond OA\" = \"#E2A3A4\",\n      \"Other\" = \"#AEACA0\"\n    )) +\n  labs(x = NULL,\n       title = \"Open Access to grant-supported biomedical research literature\",\n       subtitle = \"Journal articles and reviews in PubMed\",\n       caption = \"Data sources: PubMed, OpenAIRE, OpenAlex, cOAlition S Journal Checker Tool.\") +\n  my_theme() +\n  guides(fill = guide_legend(reverse = TRUE))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/oa_by_year_type_abs-1.png){width=2400}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe figures highlight differences in how open access is financed across the two funder communities.\nIn 2024, 94.4% of NIH-supported biomedical research articles were open access (84772 out of 89834 original research articles and reviews indexed in both PubMed and OpenAlex).\nOf those open access articles, 50.6% were enabled through individual article processing charges (APCs), while only 5.3% were covered by transformative agreements.\nThe remaining 41.1% were made available through other routes, primarily via PubMed Central.\n\nThe picture is different for European Commission-funded research.\nIn 2024, 95% of supported biomedical research articles were open access (25610 out of 26958).\nOf those, 33.4% were covered by transformative agreements, a substantially higher share than for NIH-funded research.\nThis reflectsthe wider adoption of such institutional deals in Europe.\nA further 51.2% were enabled through APCs, and 12.5% through other routes.\n\nThe comparison suggests that agreements between library consortia and publishers play an important role in making European Commission-funded publications available in Europe, raising important questions about who pays for complying with the funder's open access policy.\nThe NIH in the US did achieve a similar overall open access share, but through a different route: a much larger proportion of articles is exclusively in the \"Other\" category, likely representing articles deposited in PubMed Central or made freely available on the publisher's website after an embargo period to comply with previous NIH mandates.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}