---
title: "ORION-DBs starts FORCE11 working group"
subtitle: "Join the public webinar on Sept 4 2026 15:00-16:15 CEST"
author:
  - name: Bianca Kramer
    orcid: 0000-0002-5965-6560
date: "2026-08-04"
abstract: "To coordinate amongst current and future contributors and work towards community standards for discovery, processing, preservation and documentation, ORION-DBs is starting a [FORCE11 working group. Join our public webinar on September 4, 2026 to learn more!"
categories: [news, FORCE11, working group, public webinar]
---

With ORION-DBs, a growing set of actors are hosting large research information datasets in shared spaces, notably in Google BigQuery. 

To coordinate amongst current and future contributors and work towards community standards for discovery, processing, preservation and documentation, we are starting a [FORCE11 working group](https://force11.org/group/orion-collective-action-group-for-sharing-and-using-open-research-information-resources-online/). 

The working group will also seek to build a community around future alternatives to proprietary cloud systems for data sharing at scale and identify future paths to community-led training and development resources.

## About FORCE11
[FORCE11](https://force11.org/) brings together a diverse group of scholars, publishers, librarians, and technologists who are seeking to transform scholarly communications. FORCE11 Working Groups are a place where concrete outputs can be created through volunteer efforts and community engagement.

## Working group deliverables
Our goal is to build a community with a focus on supporting the users of Open Research Information resources to make more sophisticated and complex use of these data sources. We will do this by consolidating and expanding the resources themselves through supporting providers, gathering user stories and developing training materials. Finally we will scope pathways to technological independence from proprietary systems consistent with the needs of users.

1. Validated documentation for processing, hosting and delivering Open Research Information resources via BigQuery in the ORION DBs system
2. An expanded set of tools for processing, managing, distributing and archiving large-scale open research information resources
3. An expanded set of host providers (from the four at launch) providing access to an expanded set of ORI resources via BigQuery in the first instance
4. A set of identified use cases/user stories for the ORION DBs resources
5. Training materials including template queries and tutorials to support common use cases and user needs
6. An assessment report on technology, governance and management options for alternative technology platforms to deliver equivalent or improved functionality for ORION DBs use cases, including resource requirements and risk assessment

## Activities

*Working group meetings*
Starting in October 2026, we will organize quarterly (= 3-monthly) working group meetings, which will be held online. Working group meetings will both be an opportunity to share updates with the  full working group, and for participants to split up in subgroups (see below) to work on specific outcomes. with asynchronous work planned between working group meetings. 

*Working group organization*
We envision the working group to carry out work in 3 subgroups, each consisting of specific stakeholders: 
- **Providers** - discuss shared approaches to data processing and hosting
- **Users** - collect use cases, formulate requirements (including for access, training materials, data sources and alternative infrastructure), organize peer-to-peer support 
- **Infrastructure developers** - share and discuss approaches for alternative infrastructure

## Public webinar
We will organize a [public webinar](https://www.universiteitleiden.nl/en/events/2026/09/collective-action-for-open-research-information-introducing-orion-dbs-and-a-new-force11-working-group) on **Friday, September 4 2026** from **15:00-16:15 CEST** as part of the [CWTS Research Seminars](https://www.universiteitleiden.nl/en/events/series/cwts-research-seminars). 

The webinar will introduce the ORION-DB initiative, present a number of use cases and introduce the FORCE11 Working Group. 

If you want to learn more about ORION_DB and the planned activities of the working group, you are invited to [join the webinar online](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_YmJjYTc2MDUtMzY3OS00YWQ0LTkzYTgtN2RmNWE4YmJhMDZj%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522ca2a7f76-dbd7-4ec0-9108-6b3d524fb7c8%2522%252c%2522Oid%2522%253a%2522b10284b5-b0db-4548-8c70-eeddd68a7e0e%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=10f207c4-200a-436a-949b-64d9bf597a68&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true). Registration is not required. 


